###############################################

# Run GitHub's Super Linter against code base #

###############################################

name: GitHub's Super Linter

on:
  push:
    branches:
      - main

jobs:

  run-linters:
    name: GitHub's Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run GitHub Super Linter
        uses: github/super-linter@v4
        with:
          validate_all_codebase: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_mdl: true
