# Run GitHub's Super Linter against code base #

---

name: GitHub's Super Linter

on: push

jobs:

  run-linters:

    name: GitHub's Super Linter

    runs-on: ubuntu-latest

    steps:

      - name: Check out Git repository

        uses: actions/checkout@master

      - name: Run GitHub Super Linter

        uses: github/super-linter@main

        env:

          VALIDATE_ALL_CODEBASE: true

          VALIDATE_JAVASCRIPT_STANDARD: false

          VALIDATE_JSCPD: false

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          SUPER_LINTER_RULES_PATH: '{ "alt-require": true, "attr-lowercase": true, "attr-no-duplication": true, "attr-unsafe-chars": true, "attr-value-double-quotes": true, "attr-value-not-empty": true, "doctype-first": true, "doctype-html5": true, "head-script-disabled": true, "href-abs-or-rel": true, "html-lang-require": true, "id-class-ad-disabled": false, "id-class-value": [true, "dash"], "id-unique": true, "inline-script-disabled": true, "inline-style-disabled": true, "space-tab-mixed-disabled": true, "spec-char-escape": true, "src-not-empty": true, "style-disabled": true, "tag-pair": true, "tag-self-close": true, "tagname-lowercase": true, "title-require": true }'
