# .superlinter.yml
rules:
  id-class-value:
    enabled: true

code:
# Run GitHub's Super Linter against code base #

---

name: GitHub's Super Linter

on: push

jobs:

  run-linters:

    name: GitHub's Super Linter

    runs-on: ubuntu-latest

    steps:

      - name: Check out Git repository

        uses: actions/checkout@master

      - name: Run GitHub Super Linter

        uses: github/super-linter@main

        env:

          VALIDATE_ALL_CODEBASE: true
          
          VALIDATE_JAVASCRIPT_STANDARD: false
          
          VALIDATE_JSCPD: false
          
          DEFAULT_BRANCH: main
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          SUPER_LINTER_RULES_PATH: '{ "alt-require": true, "attr-lowercase": [ "allowReorder", "attributeName", "attributeType", "autoReverse", "baseFrequency", "baseProfile", "calcMode", "clipPathUnits", "contentScriptType", "contentStyleType", "diffuseConstant", "edgeMode", "externalResourcesRequired", "filterRes", "filterUnits", "glyphRef", "gradientTransform", "gradientUnits", "kernelMatrix", "kernelUnitLength", "keyPoints", "keySplines", "keyTimes", "lengthAdjust", "limitingConeAngle", "markerHeight", "markerUnits", "markerWidth", "maskContentUnits", "maskUnits", "numOctaves", "onBlur", "onChange", "onClick", "onFocus", "onKeyUp", "onLoad", "pathLength", "patternContentUnits", "patternTransform", "patternUnits", "pointsAtX", "pointsAtY", "pointsAtZ", "preserveAlpha", "preserveAspectRatio", "primitiveUnits", "refX", "refY", "repeatCount", "repeatDur", "requiredExtensions", "requiredFeatures", "specularConstant", "specularExponent", "spreadMethod", "startOffset", "stdDeviation", "stitchTiles", "surfaceScale", "systemLanguage", "tableValues", "targetX", "targetY", "textLength", "viewBox", "viewTarget", "xChannelSelector", "yChannelSelector", "zoomAndPan" ], "attr-no-duplication": true, "attr-unsafe-chars": true, "attr-value-double-quotes": false, "attr-value-not-empty": false, "doctype-first": false, "doctype-html5": true, "head-script-disabled": false, "href-abs-or-rel": false, "html-lang-require": false, "id-class-ad-disabled": true, "id-class-value": true, "id-unique": false, "inline-script-disabled": false, "inline-style-disabled": false, "space-tab-mixed-disabled": false, "spec-char-escape": false, "src-not-empty": true, "style-disabled": false, "tag-pair": false, "tag-self-close": false, "tagname-lowercase": true, "title-require": true }'
