# Run GitHub's Super Linter against code base

name: GitHub's Super Linter

on: push

jobs:
  run-linters:
    name: GitHub's Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Run GitHub Super Linter
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN_MDL: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_REGEX_PATTERN: "^(.*\\.(json|md|markdown|mdown|mkdn|mkd|mdwn|mdtxt|mdtext|text|txt|html|htm|css))|(.*\\.(js|ts|jsx|tsx)$|^[^:]+:(\\d+):(\\d+):\\s+(warning|error)\\s+\\[(css|scss|less)\\] Unexpected unit '(?!px)[a-z%]+' for property '\\w+' value.)|(#|0x)[0-9a-fA-F]{6}|rgb\\(\\d{1,3},\\s?\\d{1,3},\\s?\\d{1,3}\\)|hsl\\(\\d{1,3},\\s?\\d{1,3}%,\\s?\\d{1,3}%\\)$"
