linter:
  enable:
    - html
    - css
    - javascript

html:
  enable:
    - id-class-value
  disable:
    - line-length

css:
  disable:
    - zero-unit
    - hex-length
    - important-rule
    - unique-headings
    - qualified-headings
    - box-model
    - universal-selector
    - duplicate-properties

javascript:
  disable:
    - no-for-loop
    - no-ternary
    - no-trailing-spaces
